import sqlite3, io, collections, os
c=sqlite3.connect('file:D:/TLGL/.scratch/resources.db?mode=ro',uri=True)
o=io.open('agent_map_16_tex.txt','w',encoding='utf-8')
def W(*a): o.write(' '.join(str(x) for x in a)+'\n')
W('== refs from map material files (mobile_maps_source/*.mtl) by kind, resolved vs dangling')
for r in c.execute("""select kind, count(*), sum(to_hash is not null), sum(to_hash is null)
   from refs where from_path like 'mobile_maps_source/%' group by 1 order by 2 desc"""):
    W('  %-6s total=%-6d resolved=%-6d dangling=%-6d  rate %.2f%%'%(r[0],r[1],r[2],r[3],100.0*r[2]/r[1]))
W('\n== refs from .scene files')
for r in c.execute("select kind,count(*),sum(to_hash is not null) from refs where from_path like 'mobile_maps/%' group by 1 order by 2 desc"):
    W('  ',r)
W('\n== GLOBAL .tga resolution: all refs kind=.tga')
for r in c.execute("select sum(to_hash is not null), count(*) from refs where kind='.tga'"): W('  resolved %s / %s = %.2f%%'%(r[0],r[1],100.0*r[0]/r[1]))
W('\n== named .tga resources by top dir')
for r in c.execute("select dir,count(*) from resources where ext='.tga' and named=1 group by 1 order by 2 desc limit 10"): W('  ',r)
W('\n== texture resources: named vs unnamed')
for r in c.execute("select named,count(*) from resources where type='texture' group by 1"): W('  ',r)
W('\n== any resource path mentioning lightmap/lm/_lm/.lmt ?')
for r in c.execute("select count(*) from resources where lower(path) like '%lightmap%'"): W('   lightmap in path:',r)
for r in c.execute("select count(*) from resources where lower(name) like '%guangtu%' or lower(name) like '%_lm%' or lower(name) like 'lm_%'"): W('   lm-ish names:',r)
W('== refs names that look like lightmaps')
for r in c.execute("select name,count(*) from refs where lower(name) like '%light%' or lower(name) like '%lm%' group by 1 order by 2 desc limit 10"): W('  ',r)
W('\n== sfl files (JBCF) in mobile_maps: refs out of them')
for r in c.execute("select from_path,name,kind,to_hash from refs where from_path like 'mobile_maps/%.sfl' limit 15"): W('  ',r)
for r in c.execute("select count(*), count(distinct from_path) from refs where from_path like 'mobile_maps/%.sfl'"): W('  sfl refs total/paths:',r)
o.close(); print('ok')
