import sqlite3, io, collections, re, os
c=sqlite3.connect('file:D:/TLGL/.scratch/resources.db?mode=ro',uri=True)
o=io.open('agent_map_28_final.txt','w',encoding='utf-8')
def W(*a): o.write(' '.join(str(x) for x in a)+'\n')
W('== type/subtype of NAMED .mesh')
for r in c.execute("select type,subtype,count(*) from resources where ext='.mesh' and named=1 group by 1,2"): W('  ',r)
W('== self_path / src populated?')
for r in c.execute("select count(*) from resources where self_path is not null and self_path<>''"): W('  self_path non-empty:',r)
for r in c.execute("select count(*) from resources where src is not null and src<>''"): W('  src non-empty:',r)
for r in c.execute("select hash,path,self_path,src from resources where named=0 limit 3"): W('  ',r)
W('== props column sample')
for r in c.execute("select hash,props from resources limit 3"): W('  ',r)
W('\n== records vs resources')
W('  records rows:',c.execute("select count(*) from records").fetchone()[0],' resources:',c.execute("select count(*) from resources").fetchone()[0])
W('  records with hash not in resources:',c.execute("select count(*) from records r left join resources s on s.hash=r.hash where s.hash is null").fetchone()[0])
W('  distinct hashes in records:',c.execute("select count(distinct hash) from records").fetchone()[0])
W('\n== meta table')
for r in c.execute("select key,value from meta"): W('  ',r)
# cfg terrain / mesh totals with a cleaner parse
raw=open('out/tree/ResourcePath.cfg','rb').read()
i=0; paths=[]
PRE=re.compile(rb'(mobile_maps_source|mobile_maps|data|ui|scripts|settings|engine)/')
ms=[m.start() for m in PRE.finditer(raw)]
W('\n== cfg: raw counts of key substrings')
for k in [b'/terrain/', b'.TerrainInfo', b'mobile_maps_source/decal', b'.mesh', b'.tga', b'.scene', b'.map']:
    n=raw.count(k)
    W('   %-24s %6d'%(k.decode(),n))
mm=re.findall(rb'mobile_maps/[0-9A-Za-z_\-\.]+/terrain/[0-9A-Za-z_\-\.]+?\.(?:tga|TerrainInfo|dat)',raw)
W('   terrain/* files matched: %d ; distinct: %d'%(len(mm),len(set(mm))))
for x in mm[:8]: W('     ',x.decode('latin1'))
msh=re.findall(rb'mobile_maps_source/[0-9A-Za-z_\-/\.]+?\.mesh',raw)
W('   mobile_maps_source/*.mesh matched: %d distinct %d'%(len(msh),len(set(msh))))
db=set(p.lower() for (p,) in c.execute("select path from resources where named=1"))
absent=[x.decode('latin1').lower() for x in dict.fromkeys(msh) if x.decode('latin1').lower() not in db]
W('   of those, ABSENT from resources.db: %d (%.1f%%)'%(len(absent),100.0*len(absent)/max(1,len(set(msh)))))
W('   absent examples:',absent[:8])
tg=re.findall(rb'mobile_maps/[0-9A-Za-z_\-/\.]+?\.tga',raw)
W('\n   mobile_maps/*.tga in cfg: %d distinct %d ; in db: %d'%(len(tg),len(set(tg)),sum(1 for x in set(tg) if x.decode('latin1').lower() in db)))
o.close();print('ok')
