import sys, sqlite3, collections
c = sqlite3.connect('file:D:/TLGL/.scratch/resources.db?mode=ro', uri=True)
q = lambda s, a=(): c.execute(s, a).fetchall()

print('#### ITEM 2: unnamed grid753 scene tables ####')
print('by subtype/named:')
for r in q("select subtype,named,count(*),sum(original),sum(stored) from resources where type='scene' group by 1,2 order by 3 desc"):
    print('  ', r)
un = [r[0] for r in q("select hash from resources where subtype='grid753' and named=0")]
print('unnamed grid753 count:', len(un))
print('their sum(original):', q("select sum(original),min(original),max(original),avg(original) from resources where subtype='grid753' and named=0")[0])
print('their dir/name values:', q("select distinct dir,name,path,self_path,src from resources where subtype='grid753' and named=0 limit 5"))
print('pak spread:', q("select pak,count(*) from resources where subtype='grid753' and named=0 group by 1 order by 2 desc"))
print('gen spread:', q("select gen,count(*) from resources where subtype='grid753' and named=0 group by 1 order by 2 limit 12"))
print('props sample:', q("select hash,props,original from resources where subtype='grid753' and named=0 limit 6"))

ph = ','.join('?' * len(un))
print()
print('referenced as refs.to_hash :', q('select count(*) from refs where to_hash in (%s)' % ph, un)[0][0])
print('referenced as relations.to  :', q('select count(*) from relations where to_hash in (%s)' % ph, un)[0][0])
print('referenced as relations.from:', q('select count(*) from relations where from_hash in (%s)' % ph, un)[0][0])
print('in assets.primary_hash      :', q('select count(*) from assets where primary_hash in (%s)' % ph, un)[0][0])
print('in amembers.hash            :', q('select count(*) from amembers where hash in (%s)' % ph, un)[0][0])
print('in blobs.hash               :', q('select count(*) from blobs where hash in (%s)' % ph, un)[0][0])
print('named scenes referenced by refs (control):',
      q("select count(*) from refs where to_hash in (select hash from resources where subtype='grid753' and named=1)")[0][0])
print()
print('dirs of NAMED grid753 (distinct map dirs):', q("select count(distinct dir) from resources where subtype='grid753' and named=1")[0][0])
print('map dirs that contain at least one unnamed? (unnamed have no dir) -> check dangling:')
print('  dangling ext rows:', q("select ext,count(*),sum(n_refs) from dangling group by 1 order by 2 desc limit 10"))
print('  dangling .scene:', q("select * from dangling where ext='.scene' limit 5"))
print()
print('#### ITEM 1: set/copy .scene ####')
for r in q("select type,subtype,ext,count(*),sum(original),sum(stored),max(original),min(original) from resources where type in ('set','copy') or subtype='copy' and ext='.scene' group by 1,2,3 order by 4 desc"):
    print('  ', r)
print('  .scene by type:', q("select type,count(*),sum(original),max(original) from resources where ext='.scene' group by 1 order by 3 desc"))
print('  set/copy ext spread:', q("select ext,count(*),sum(original) from resources where type='set' group by 1 order by 2 desc"))
print('  all type=set named?', q("select named,count(*) from resources where type='set' group by 1"))
print('  top 8 largest type=set ext=.scene:', q("select hash,path,original,stored,props from resources where type='set' and ext='.scene' order by original desc limit 8"))
print('  dir pattern of type=.scene set:', q("select substr(dir,1,16),count(*) from resources where type='set' and ext='.scene' group by 1 order by 2 desc limit 10"))

print()
print('#### ITEM 3: .tani / GATA ####')
print(q("select type,subtype,ext,count(*),sum(original),sum(stored),min(original),max(original) from resources where ext='.tani' or type='GATA' group by 1,2,3"))
print('  named?', q("select named,count(*) from resources where ext='.tani' group by 1"))
print('  dirs:', q("select distinct substr(dir,1,20) from resources where ext='.tani' limit 10"))
print('  sample paths:', q("select hash,path,original,props from resources where ext='.tani' limit 6"))
print('  props spread:', q("select props,count(*) from resources where ext='.tani' group by 1 order by 2 desc limit 10"))

print()
print('#### ITEM 4: .nav / NAVF ####')
print(q("select type,subtype,ext,named,count(*),sum(original),min(original),max(original) from resources where ext='.nav' or type='NAVF' group by 1,2,3,4"))
print('  nav named paths:', q("select hash,path,original,props from resources where ext='.nav' order by original desc limit 8"))
print('  NAVF unnamed props spread:', q("select props,count(*) from resources where type='NAVF' group by 1 order by 2 desc limit 8"))

print()
print('#### ITEM 5: mapref/tab280 ####')
print(q("select type,subtype,named,count(*),sum(original),min(original),max(original) from resources where type='mapref' group by 1,2,3"))
print('  props spread:', q("select props,count(*) from resources where type='mapref' group by 1 order by 2 desc limit 10"))
print('  dirs:', q("select distinct dir from resources where type='mapref' limit 5"))

print()
print('#### ITEM 6: geom/raw ####')
print(q("select type,subtype,named,count(*),sum(original),sum(stored),min(original),max(original) from resources where type='geom' group by 1,2,3"))
print('  distinct original sizes:', q("select original,count(*) from resources where type='geom' group by 1 order by 2 desc limit 12"))
print('  props spread:', q("select props,count(*) from resources where type='geom' group by 1 order by 2 desc limit 8"))
print('  mesh (named) for comparison:', q("select type,subtype,ext,named,count(*),sum(original) from resources where ext='.mesh' group by 1,2,3,4"))
print('  mesh original size distinct:', q("select count(distinct original) from resources where ext='.mesh' and named=1"))
