const list = await (await fetch("http://127.0.0.1:9222/json/list")).json();
const page = list.find((t) => t.type === "page" && t.webSocketDebuggerUrl);
const ws = new WebSocket(page.webSocketDebuggerUrl);
let id = 0;
const send = (m, p = {}) => new Promise((res) => { const mid = ++id; const on = (e) => { const x = JSON.parse(e.data); if (x.id === mid) { ws.removeEventListener("message", on); res(x.result); } }; ws.addEventListener("message", on); ws.send(JSON.stringify({ id: mid, method: m, params: p })); });
await new Promise((r) => ws.addEventListener("open", r, { once: true }));
const ev = async (e) => { const r = await send("Runtime.evaluate", { expression: e, returnByValue: true, awaitPromise: true }); if (r?.exceptionDetails) return "抛错:" + r.exceptionDetails.text; return r?.result?.value; };
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
await send("Runtime.enable"); await send("Page.enable");
console.log("存着的状态：", await ev(`(localStorage.getItem("tlbb-explorer-ui")||"无").slice(0,120)`));
await ev(`localStorage.removeItem("tlbb-explorer-ui")`);
await send("Page.reload", { ignoreCache: true });
await wait(9000);
await ev(`(() => { const b=[...document.querySelectorAll("button")].find(x=>x.textContent.trim()==="资产"); b&&b.click(); return 1; })()`);
await wait(3000);
await ev(`(() => { const q=document.getElementById("q"); q.value="xiyuqiezei"; q.dispatchEvent(new Event("input",{bubbles:true})); return 1; })()`);
await wait(6000);
console.log("搜到行数：", await ev(`document.querySelectorAll(".row-item").length`));
console.log(await ev(`(() => { const r=[...document.querySelectorAll(".row-item")].find(x=>x.textContent.includes("xiyuqiezei")); if(!r) return "没点到"; r.click(); return "点了"; })()`));
await wait(4000);
await ev(`(() => { const t=document.querySelector('#dTabs .tab[data-tab="skeleton"]'); t&&t.click(); return 1; })()`);
await wait(6000);
console.log("骨表行数：", await ev(`document.querySelectorAll("#skelTable tbody tr").length`));
console.log("摘要：", await ev(`document.getElementById("skelSum").textContent`));
console.log("只有名字的骨行数：", await ev(`[...document.querySelectorAll("#skelTable tbody tr")].filter(r=>r.textContent.includes("矩阵不在 .mesh 里")).length`));
console.log("假骨在不在：", await ev(`/Bip01_|>Bone01</.test(document.getElementById("skelTable").textContent)`));
console.log("前 3 行：", await ev(`[...document.querySelectorAll("#skelTable tbody tr")].slice(0,3).map(r=>[...r.children].map(c=>c.textContent.trim()).join("|")).join(" ~~ ")`));
console.log("末 2 行：", await ev(`[...document.querySelectorAll("#skelTable tbody tr")].slice(-2).map(r=>[...r.children].map(c=>c.textContent.trim()).join("|")).join(" ~~ ")`));
ws.close();
