import sqlite3, struct, re
c = sqlite3.connect('file:D:/TLGL/.scratch/resources.db?mode=ro', uri=True)
print('== subtype for key types ==')
for t in ('geom','JBPU','GATA','NAVF','binary','tiny','mapref','set','table','missing'):
    rows = c.execute("select subtype, count(*) from resources where type=? group by 1 order by 2 desc limit 6",(t,)).fetchall()
    print(f"{t:8s}", rows)
print()
print('== geom: codec/method/flags ==')
for r in c.execute("select codec, method, count(*) from resources where type='geom' group by 1,2 order by 3 desc limit 10"):
    print('  ', r)
print()
print('== texture extless vs named ==')
print(c.execute("select named, count(*) from resources where type='texture' group by 1").fetchall())
print('== .pu sample paths ==')
for r in c.execute("select path from resources where type='JBPU' limit 5"): print('  ', r[0])
print('== .tani sample ==')
for r in c.execute("select path from resources where type='GATA' limit 5"): print('  ', r[0])
print('== geom sample paths ==')
for r in c.execute("select path from resources where type='geom' limit 5"): print('  ', r[0])
print('== NAVF sample ==')
for r in c.execute("select path from resources where type='NAVF' limit 5"): print('  ', r[0])
print('== binary sample ==')
for r in c.execute("select path, ext from resources where type='binary' limit 8"): print('  ', r[0])
print('== mapref sample ==')
for r in c.execute("select path from resources where type='mapref' limit 5"): print('  ', r[0])
print('== set/table sample ==')
for r in c.execute("select path, type from resources where type in ('set','table') limit 6"): print('  ', r[0])
print('== missing sample ==')
for r in c.execute("select path, src from resources where type='missing' limit 6"): print('  ', r[0])
print('== ani extless sample ==')
for r in c.execute("select path, subtype from resources where type='ani' and (ext is null or ext='') limit 5"): print('  ', r[0])
