import collections, sqlite3, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
c = sqlite3.connect('file:D:/TLGL/.scratch/resources.db?mode=ro', uri=True)
q = lambda s: c.execute(s).fetchall()
print('== anonymous textures (named=0) ==')
dims = q("select width,height,count(*) n from resources where type='texture' and named=0 group by 1,2 order by n desc limit 12")
for w,h,n in dims: print(f'  {w}x{h}: {n}')
np2 = q("select sum((width & (width-1) = 0) and (height & (height-1) = 0)), count(*) from resources where type='texture' and named=0")[0]
print(f'  power-of-two dims: {np2[0]}/{np2[1]}')
print('  codec:', q("select codec,count(*) from resources where type='texture' and named=0 group by 1 order by 2 desc limit 8"))
print('  mips:', q("select mips,count(*) from resources where type='texture' and named=0 group by 1 order by 2 desc limit 6"))
print('  distinct filecrc:', q("select count(distinct filecrc), count(*) from resources where type='texture' and named=0")[0])
print('  original size: distinct', q("select count(distinct original) from resources where type='texture' and named=0")[0][0])
print('  pak:', q("select pak,count(*) from resources where type='texture' and named=0 group by 1 order by 2 desc limit 8"))
print('== named textures (contrast) ==')
print('  codec:', q("select codec,count(*) from resources where type='texture' and named=1 group by 1 order by 2 desc limit 6"))
print('  top dims:', q("select width,height,count(*) from resources where type='texture' and named=1 group by 1,2 order by 3 desc limit 6"))
print('== geom blocks ==')
print('  original distinct:', q("select count(distinct original), count(*), min(original), max(original) from resources where type='geom'")[0])
print('== decode-failure scan: the 1 undecodable ==')
print('  props/src null-ish:', q("select count(*) from resources where type='texture' and named=0 and (props is null or props='')")[0])
